name: auto PR swiftLint

on:
  pull_request:
    branches: [ develop ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch (head)
      uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/head

    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@master
      env:
        DIFF_BASE: ${{ github.base_ref }}

    - name: Add PR Comment
      if: ${{ success() }}
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## All File Checked ✅
          | ✅     | Auto Pull Request SwiftLint Success!!!!     |
          |---    |----------------------------------------------    |
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: false
